version: '3.9'

services:
  app:
    image: 'datatransfersheduler:1.0'
    build:
      context: .
    container_name: datatransfersheduler-service
    ports:
      - 9191:8080
    environment:
      - DB_URL = jdbc:postgresql://host.docker.internal:5432/DataTransferDB
      - SCHEDULER_SERVICE_URL = http://host.docker.internal:9090/v1/baseCustomer/getAllCustomerWithVersion?version=